# SD202 TP3 - Views, Updates and Database Design

The objectives for this TP are:

1. Create and use SQL Views
2. Update database content
3. Design the database schema for a marketplace


For the first 2 parts we will use the _wine_ database and the Tables created in TP2.

A reminder of the wine database schema:

+-----------------------------------------+
|                 Master1                 |
+-----------------------------------------+
| NV:      Wine number                    |
| CRU:     Vineyard or group of vineyards |
| DEGRE:   Alcohol content                |
| MILL:    Vintage year                   |
| QTE:     Number of bottles harvested    |
| NP:      Producer number                |
| NOM:     Producer's last name           |
| PRENOM:  Producer's first name          |
| REGION:  Wine growing region            |
+-----------------------------------------+

+-------------------------------------------------------------------+
|                              Master2                              |
+-------------------------------------------------------------------+
| NV:      Wine number                                              |
| CRU:     Vineyard or group of vineyards                           |
| DEGRE:   Alcohol content                                          |
| MILL:    Vintage year                                             |
| DATES:   Buying date                                              |
| LIEU:    Place where the wine was sold                            |
| QTE:     Number of bottles bought                                 |
| NB:      Client (buveur) number                                   |
| NON:     Client's last name                                       |
| PRENOM:  Client's first name                                      |
| TYPE:    Type of client by volume of purchases                    |
| REGION:  Administrative Region (different to wine growing region) |
+-------------------------------------------------------------------+

In [1]:
import sqlite3

In [2]:
def printSchema(connection):
    ### Source: http://stackoverflow.com/a/35092773/4765776
    for (tableName,) in connection.execute(
        """
        select NAME from SQLITE_MASTER where TYPE='table' order by NAME;
        """
    ):
        print("{}:".format(tableName))
        for (
            columnID, columnName, columnType,
            columnNotNull, columnDefault, columnPK,
        ) in connection.execute("pragma table_info('{}');".format(tableName)):
            print("  {id}: {name}({type}){null}{default}{pk}".format(
                id=columnID,
                name=columnName,
                type=columnType,
                null=" not null" if columnNotNull else "",
                default=" [{}]".format(columnDefault) if columnDefault else "",
                pk=" *{}".format(columnPK) if columnPK else "",
            ))

In [5]:
conn = sqlite3.connect('wine.db')
c = conn.cursor()
print("Database schema:")
printSchema(conn)

Database schema:

Again, we recommend inline %sql as an alternative to the sqlite3 package

In [6]:
%load_ext sql
%sql sqlite:///wine.db

Recreate the Tables in 3NF/BCNF from Master2 as you did in the TP2

___
# PART I: CREATE AND USE VIEWS

A view is a virtual table based on the result-set of an SQL statement. Views are stored in the database with an associated name.

Views are created following the syntax:

```sql
CREATE VIEW view_name AS
SELECT column1, column2.....
FROM table_name
WHERE [condition];
```

An useful command is:

```sql
DROP VIEW IF EXISTS view_name;
```


__Note:__ Use it with caution (only drop something if you are sure)

__1.1__ Create a view 'bons_buveurs' with the clients (buveurs) of type 'gros' or 'moyen'.

In [ ]:
# Test
%sql SELECT * FROM bons_buveurs ORDER BY nb;

Done.

[(2, u'Artaud', u'Antonin', u'moyen'),
 (3, u'Aron', u'Raymond', u'gros'),
 (4, u'Apollinaire', u'Guillaume', u'moyen'),
 (6, u'Arrabal', u'Fernando', u'gros'),
 (7, u'Anouilh', u'Jean', u'moyen'),
 (8, u'Aragon', u'Louis', u'gros'),
 (10, u'Andersen', u'Yann', u'gros'),
 (12, u'Bataille', u'Georges', u'moyen'),
 (13, u'Barthes', u'Roland', u'moyen'),
 (14, u'Bory', u'Jean Louis', u'gros'),
 (16, u'Balzac', u'Honore de', u'moyen'),
 (18, u'Celine', u'Louis Ferdinand', u'gros'),
 (19, u'Ciceron', None, u'gros'),
 (20, u'Chateaubriand', u'Francois-Rene de', u'moyen'),
 (22, u'Cocteau', u'Jean', u'gros'),
 (24, u'Courrier', u'Paul Louis', u'moyen'),
 (26, u'Diderot', u'Denis', u'moyen'),
 (27, u'Dumas', u'Alexandre', u'gros'),
 (28, u'Dostoievsky', u'Fiodor', u'gros'),
 (31, u'Dante', None, u'gros'),
 (32, u'Eluard', u'Paul', u'moyen'),
 (33, u'Flaubert', u'Gustave', u'moyen'),
 (35, u'Fromentin', u'Eugene', u'gros'),
 (39, u'Montesquieu', None, u'gros'),
 (42, u'Goethe', u'Johann Wolfgang von', u'moyen'),
 (43, u'Musset', u'Alfred de', u'gros'),
 (46, u'Hugo', u'Victor', u'moyen'),
 (48, u'Hardy', u'Thomas', u'moyen'),
 (50, u'Lautreamont', None, u'moyen'),
 (53, u'Lamartine', u'Alphonse de', u'gros'),
 (55, u'Michelet', u'Jules', u'gros'),
 (57, u'Marx', u'Karl', u'gros'),
 (58, u'Marivaux', u'Pierre Carlet de Chamblain de', u'gros'),
 (60, u'Ovide', None, u'gros'),
 (62, u'Proust', u'Marcel', u'moyen'),
 (64, u'Platon', None, u'gros'),
 (66, u'Perec', u'Georges', u'gros'),
 (68, u'Prevert', u'Jacques', u'gros'),
 (70, u'Paulhan', u'Jean', u'gros'),
 (72, u'Rabelais', u'Francois', u'gros'),
 (73, u'Poe', u'Allan Edgard', u'moyen'),
 (75, u'Ronsard', u'Pierre', u'moyen'),
 (76, u'Racine', u'Jean', u'gros'),
 (78, u'Sandier', u'Jules', u'moyen'),
 (79, u'Sade', u'Donatien Alphonse Fran\xbf\xbfs de', u'gros'),
 (81, u'Sartre', u'Jean-Paul', u'gros'),
 (83, u'Sophocle', None, u'gros'),
 (84, u'Sue', u'Eugene', u'moyen'),
 (86, u'Saint Exupery', u'Antoine de', u'gros'),
 (87, u'Segur', u'Comtesse de', u'gros'),
 (91, u'Verlaine', u'Paul', u'gros'),
 (93, u'Virgile', None, u'gros'),
 (94, u'Zola', u'Emile', u'moyen'),
 (95, u'Zorn', u'Fritz', u'moyen'),
 (98, u'Maturin', u'Robert', u'gros'),
 (99, u'Cesar', u'Jules', u'gros')]

__1.2__ Create the view 'buveurs_asec' with clients (buveurs) who have not bought any wine.

Done.
Done.

[]

In [ ]:
# Test
%sql SELECT * FROM buveurs_asec ORDER BY nb;

Done.

[(11, u'Breton', u'Andre', u'petit'),
 (13, u'Barthes', u'Roland', u'moyen'),
 (16, u'Balzac', u'Honore de', u'moyen'),
 (18, u'Celine', u'Louis Ferdinand', u'gros'),
 (20, u'Chateaubriand', u'Francois-Rene de', u'moyen'),
 (21, u'Corbiere', u'Tristan', u'petit'),
 (23, u'Corneille', u'Pierre', u'petit'),
 (25, u'Char', u'Rene', u'petit'),
 (27, u'Dumas', u'Alexandre', u'gros'),
 (29, u'Fournier', u'Alain', u'petit'),
 (32, u'Eluard', u'Paul', u'moyen'),
 (34, u'Mauriac', u'Francois', u'petit'),
 (35, u'Fromentin', u'Eugene', u'gros'),
 (36, u'Maurois', u'Andre', u'petit'),
 (37, u'Freud', u'Sigmund', u'petit'),
 (39, u'Montesquieu', None, u'gros'),
 (42, u'Goethe', u'Johann Wolfgang von', u'moyen'),
 (43, u'Musset', u'Alfred de', u'gros'),
 (46, u'Hugo', u'Victor', u'moyen'),
 (47, u'Gary', u'Romain', u'petit'),
 (51, u'Lafargue', u'Paul', u'petit'),
 (53, u'Lamartine', u'Alphonse de', u'gros'),
 (54, u'Aurele', u'Marc', u'petit'),
 (55, u'Michelet', u'Jules', u'gros'),
 (56, u'Nerval', u'Gerard de', u'petit'),
 (57, u'Marx', u'Karl', u'gros'),
 (59, u'Nietzsche', u'Friedrich', u'petit'),
 (63, u'Maupassant', u'Guy de', u'petit'),
 (64, u'Platon', None, u'gros'),
 (65, u'Pascal', u'Blaise', u'petit'),
 (66, u'Perec', u'Georges', u'gros'),
 (67, u'Nin', u'Anais', u'petit'),
 (68, u'Prevert', u'Jacques', u'gros'),
 (69, u'Queneau', u'Raymond', u'petit'),
 (70, u'Paulhan', u'Jean', u'gros'),
 (71, u'Radiguet', u'Raymond', u'petit'),
 (72, u'Rabelais', u'Francois', u'gros'),
 (73, u'Poe', u'Allan Edgard', u'moyen'),
 (74, u'Rimbaud', u'Arthur', u'petit'),
 (76, u'Racine', u'Jean', u'gros'),
 (77, u'Rousseau', u'Jean-Jacques', u'petit'),
 (78, u'Sandier', u'Jules', u'moyen'),
 (79, u'Sade', u'Donatien Alphonse Fran\xbf\xbfs de', u'gros'),
 (81, u'Sartre', u'Jean-Paul', u'gros'),
 (83, u'Sophocle', None, u'gros'),
 (84, u'Sue', u'Eugene', u'moyen'),
 (85, u'Segalen', u'Victor', u'petit'),
 (86, u'Saint Exupery', u'Antoine de', u'gros'),
 (87, u'Segur', u'Comtesse de', u'gros'),
 (88, u'Shakespeare', u'William', u'petit'),
 (89, u'Stendhal', None, u'petit'),
 (90, u'Vian', u'Boris', u'petit'),
 (91, u'Verlaine', u'Paul', u'gros'),
 (93, u'Virgile', None, u'gros'),
 (95, u'Zorn', u'Fritz', u'moyen'),
 (98, u'Maturin', u'Robert', u'gros'),
 (99, u'Cesar', u'Jules', u'gros')]

__1.3__ Create the view 'buveurs_achats' complementary to the previous one.

Done.
Done.

[]

In [ ]:
# Test
%sql SELECT * FROM buveurs_achats ORDER BY nb;

Done.

[(1, u'Aristote', None, u'petit'),
 (2, u'Artaud', u'Antonin', u'moyen'),
 (3, u'Aron', u'Raymond', u'gros'),
 (4, u'Apollinaire', u'Guillaume', u'moyen'),
 (5, u'Audiberti', u'Jacques', u'petit'),
 (6, u'Arrabal', u'Fernando', u'gros'),
 (7, u'Anouilh', u'Jean', u'moyen'),
 (8, u'Aragon', u'Louis', u'gros'),
 (9, u'Ajar', u'Emile', u'petit'),
 (10, u'Andersen', u'Yann', u'gros'),
 (12, u'Bataille', u'Georges', u'moyen'),
 (14, u'Bory', u'Jean Louis', u'gros'),
 (15, u'Baudelaire', u'Charles', u'petit'),
 (17, u'Camus', u'Albert', u'petit'),
 (19, u'Ciceron', None, u'gros'),
 (22, u'Cocteau', u'Jean', u'gros'),
 (24, u'Courrier', u'Paul Louis', u'moyen'),
 (26, u'Diderot', u'Denis', u'moyen'),
 (28, u'Dostoievsky', u'Fiodor', u'gros'),
 (30, u'La Fontaine', u'Jean de', u'petit'),
 (31, u'Dante', None, u'gros'),
 (33, u'Flaubert', u'Gustave', u'moyen'),
 (38, u'Montaigne', u'Michel de', u'petit'),
 (40, u'Moliere', None, u'petit'),
 (41, u'Gauthier', u'Theophile', u'petit'),
 (44, u'Gide', u'Andre', u'petit'),
 (45, u'Giono', u'Jean', u'petit'),
 (48, u'Hardy', u'Thomas', u'moyen'),
 (49, u'Kafka', u'Franz', u'petit'),
 (50, u'Lautreamont', None, u'moyen'),
 (52, u'Carroll', u'Lewis', u'petit'),
 (58, u'Marivaux', u'Pierre Carlet de Chamblain de', u'gros'),
 (60, u'Ovide', None, u'gros'),
 (61, u'Mallarme', u'Stephane', u'petit'),
 (62, u'Proust', u'Marcel', u'moyen'),
 (75, u'Ronsard', u'Pierre', u'moyen'),
 (80, u'Sand', u'Georges', u'petit'),
 (82, u'Roussel', u'Rene', u'petit'),
 (92, u'Verne', u'Jules', u'petit'),
 (94, u'Zola', u'Emile', u'moyen'),
 (96, u'Wilde', u'Oscar', u'petit'),
 (97, u'Vigny', u'Alfred de', u'petit'),
 (100, u'Woolf', u'Virginia', u'petit')]

__1.4__ Create the view 'q83pl' (LIEU, CRU, QTE_BUE) that provides by LIEU and CRU the total quantities bought in 1983 by all the clients (buveurs).

Done.
Done.

[]

In [ ]:
# Test
%sql SELECT * FROM q83pl;

Done.

[(u'CAEN', u'Seyssel', 3),
 (u'LILLE', u'Pommard', 5),
 (u'LYON', u'Beaujolais Villages', 10),
 (u'LYON', u'Julienas', 2),
 (u'PARIS', u'Beaujolais Primeur', 4),
 (u'PARIS', u'Coteaux du Tricastin', 1),
 (u'PARIS', u'Pouilly Vinzelles', 3),
 (u'RENNES', u'Mercurey', 1),
 (u'ROCQUENCOURT', u'Beaujolais Villages', 260),
 (u'ROCQUENCOURT', u'Saint Amour', 80)]

__1.5__ Can we define the same view with ascending order over the attribute QTE? Provide an explanation for your answer.

Answer:

___
# PART II: UPDATE DATABASE CONTENT

The syntax for the Update statement is:

```sql
UPDATE table_name
SET column1 = value1, column2 = value2...., columnN = valueN
WHERE [condition];
```

The syntax for the Insert statement is:

```sql
INSERT INTO TABLE_NAME [(column1, column2, column3,...columnN)]  
VALUES (value1, value2, value3,...valueN);
```


Database updates are commited automatically in Jupyter/Python. _Transactions_ are an option to control and reverse changes. Additionally we can just reload a backup of the database (NOT an option in deployed systems)

__Note:__ Different to other Database Management Systems, SQLite views are read-only and so you may not execute a DELETE, INSERT or UPDATE statement on a view.

__2.1__ Create a table 'RBB' with the same schema as 'bons_buveurs' which contains the tuples selected from 'bons_buveurs'

Done.
Done.

[]

In [ ]:
# Test
%sql SELECT * FROM RBB;

Done.

[(2, u'Artaud', u'Antonin', u'moyen'),
 (3, u'Aron', u'Raymond', u'gros'),
 (4, u'Apollinaire', u'Guillaume', u'moyen'),
 (6, u'Arrabal', u'Fernando', u'gros'),
 (7, u'Anouilh', u'Jean', u'moyen'),
 (8, u'Aragon', u'Louis', u'gros'),
 (10, u'Andersen', u'Yann', u'gros'),
 (12, u'Bataille', u'Georges', u'moyen'),
 (13, u'Barthes', u'Roland', u'moyen'),
 (14, u'Bory', u'Jean Louis', u'gros'),
 (16, u'Balzac', u'Honore de', u'moyen'),
 (18, u'Celine', u'Louis Ferdinand', u'gros'),
 (19, u'Ciceron', None, u'gros'),
 (20, u'Chateaubriand', u'Francois-Rene de', u'moyen'),
 (22, u'Cocteau', u'Jean', u'gros'),
 (24, u'Courrier', u'Paul Louis', u'moyen'),
 (26, u'Diderot', u'Denis', u'moyen'),
 (27, u'Dumas', u'Alexandre', u'gros'),
 (28, u'Dostoievsky', u'Fiodor', u'gros'),
 (31, u'Dante', None, u'gros'),
 (32, u'Eluard', u'Paul', u'moyen'),
 (33, u'Flaubert', u'Gustave', u'moyen'),
 (35, u'Fromentin', u'Eugene', u'gros'),
 (39, u'Montesquieu', None, u'gros'),
 (42, u'Goethe', u'Johann Wolfgang von', u'moyen'),
 (43, u'Musset', u'Alfred de', u'gros'),
 (46, u'Hugo', u'Victor', u'moyen'),
 (48, u'Hardy', u'Thomas', u'moyen'),
 (50, u'Lautreamont', None, u'moyen'),
 (53, u'Lamartine', u'Alphonse de', u'gros'),
 (55, u'Michelet', u'Jules', u'gros'),
 (57, u'Marx', u'Karl', u'gros'),
 (58, u'Marivaux', u'Pierre Carlet de Chamblain de', u'gros'),
 (60, u'Ovide', None, u'gros'),
 (62, u'Proust', u'Marcel', u'moyen'),
 (64, u'Platon', None, u'gros'),
 (66, u'Perec', u'Georges', u'gros'),
 (68, u'Prevert', u'Jacques', u'gros'),
 (70, u'Paulhan', u'Jean', u'gros'),
 (72, u'Rabelais', u'Francois', u'gros'),
 (73, u'Poe', u'Allan Edgard', u'moyen'),
 (75, u'Ronsard', u'Pierre', u'moyen'),
 (76, u'Racine', u'Jean', u'gros'),
 (78, u'Sandier', u'Jules', u'moyen'),
 (79, u'Sade', u'Donatien Alphonse Fran\xbf\xbfs de', u'gros'),
 (81, u'Sartre', u'Jean-Paul', u'gros'),
 (83, u'Sophocle', None, u'gros'),
 (84, u'Sue', u'Eugene', u'moyen'),
 (86, u'Saint Exupery', u'Antoine de', u'gros'),
 (87, u'Segur', u'Comtesse de', u'gros'),
 (91, u'Verlaine', u'Paul', u'gros'),
 (93, u'Virgile', None, u'gros'),
 (94, u'Zola', u'Emile', u'moyen'),
 (95, u'Zorn', u'Fritz', u'moyen'),
 (98, u'Maturin', u'Robert', u'gros'),
 (99, u'Cesar', u'Jules', u'gros')]

__2.2__ Update the table you used to create 'bons_buveurs': Change the 'type' to 'gros' if the total of quantities bought is over 100.

Find the instances to update (schema may be different from the one in your table)

Done.

[(2, u'Artaud', u'Antonin', u'moyen', 583),
 (5, u'Audiberti', u'Jacques', u'petit', 113),
 (9, u'Ajar', u'Emile', u'petit', 140),
 (44, u'Gide', u'Andre', u'petit', 171)]

Update instances

4 rows affected.

[]

__2.3__ Compare the content of _table_ 'RBB' and the _view_ 'bons_buveurs' after the update. What differences do you see? Explain

Answer:

__2.4__ Create a table 'RBA' with the same schema as 'buveurs_asec' which contains the tuples selected from 'buveurs_asec'

Done.

[]

In [ ]:
# Test
%sql SELECT * FROM RBA

Done.

[(11, u'Breton', u'Andre', u'petit'),
 (13, u'Barthes', u'Roland', u'moyen'),
 (16, u'Balzac', u'Honore de', u'moyen'),
 (18, u'Celine', u'Louis Ferdinand', u'gros'),
 (20, u'Chateaubriand', u'Francois-Rene de', u'moyen'),
 (21, u'Corbiere', u'Tristan', u'petit'),
 (23, u'Corneille', u'Pierre', u'petit'),
 (25, u'Char', u'Rene', u'petit'),
 (27, u'Dumas', u'Alexandre', u'gros'),
 (29, u'Fournier', u'Alain', u'petit'),
 (32, u'Eluard', u'Paul', u'moyen'),
 (34, u'Mauriac', u'Francois', u'petit'),
 (35, u'Fromentin', u'Eugene', u'gros'),
 (36, u'Maurois', u'Andre', u'petit'),
 (37, u'Freud', u'Sigmund', u'petit'),
 (39, u'Montesquieu', None, u'gros'),
 (42, u'Goethe', u'Johann Wolfgang von', u'moyen'),
 (43, u'Musset', u'Alfred de', u'gros'),
 (46, u'Hugo', u'Victor', u'moyen'),
 (47, u'Gary', u'Romain', u'petit'),
 (51, u'Lafargue', u'Paul', u'petit'),
 (53, u'Lamartine', u'Alphonse de', u'gros'),
 (54, u'Aurele', u'Marc', u'petit'),
 (55, u'Michelet', u'Jules', u'gros'),
 (56, u'Nerval', u'Gerard de', u'petit'),
 (57, u'Marx', u'Karl', u'gros'),
 (59, u'Nietzsche', u'Friedrich', u'petit'),
 (63, u'Maupassant', u'Guy de', u'petit'),
 (64, u'Platon', None, u'gros'),
 (65, u'Pascal', u'Blaise', u'petit'),
 (66, u'Perec', u'Georges', u'gros'),
 (67, u'Nin', u'Anais', u'petit'),
 (68, u'Prevert', u'Jacques', u'gros'),
 (69, u'Queneau', u'Raymond', u'petit'),
 (70, u'Paulhan', u'Jean', u'gros'),
 (71, u'Radiguet', u'Raymond', u'petit'),
 (72, u'Rabelais', u'Francois', u'gros'),
 (73, u'Poe', u'Allan Edgard', u'moyen'),
 (74, u'Rimbaud', u'Arthur', u'petit'),
 (76, u'Racine', u'Jean', u'gros'),
 (77, u'Rousseau', u'Jean-Jacques', u'petit'),
 (78, u'Sandier', u'Jules', u'moyen'),
 (79, u'Sade', u'Donatien Alphonse Fran\xbf\xbfs de', u'gros'),
 (81, u'Sartre', u'Jean-Paul', u'gros'),
 (83, u'Sophocle', None, u'gros'),
 (84, u'Sue', u'Eugene', u'moyen'),
 (85, u'Segalen', u'Victor', u'petit'),
 (86, u'Saint Exupery', u'Antoine de', u'gros'),
 (87, u'Segur', u'Comtesse de', u'gros'),
 (88, u'Shakespeare', u'William', u'petit'),
 (89, u'Stendhal', None, u'petit'),
 (90, u'Vian', u'Boris', u'petit'),
 (91, u'Verlaine', u'Paul', u'gros'),
 (93, u'Virgile', None, u'gros'),
 (95, u'Zorn', u'Fritz', u'moyen'),
 (98, u'Maturin', u'Robert', u'gros'),
 (99, u'Cesar', u'Jules', u'gros')]

__2.5__ Insert a tuple (101, 'your last name', 'your first name', 'your type of purchases(petit, moyen, or gros)') to 'RBA'

1 rows affected.

[]

In [ ]:
# Test
%sql SELECT * FROM RBA

Done.

[(11, u'Breton', u'Andre', u'petit'),
 (13, u'Barthes', u'Roland', u'moyen'),
 (16, u'Balzac', u'Honore de', u'moyen'),
 (18, u'Celine', u'Louis Ferdinand', u'gros'),
 (20, u'Chateaubriand', u'Francois-Rene de', u'moyen'),
 (21, u'Corbiere', u'Tristan', u'petit'),
 (23, u'Corneille', u'Pierre', u'petit'),
 (25, u'Char', u'Rene', u'petit'),
 (27, u'Dumas', u'Alexandre', u'gros'),
 (29, u'Fournier', u'Alain', u'petit'),
 (32, u'Eluard', u'Paul', u'moyen'),
 (34, u'Mauriac', u'Francois', u'petit'),
 (35, u'Fromentin', u'Eugene', u'gros'),
 (36, u'Maurois', u'Andre', u'petit'),
 (37, u'Freud', u'Sigmund', u'petit'),
 (39, u'Montesquieu', None, u'gros'),
 (42, u'Goethe', u'Johann Wolfgang von', u'moyen'),
 (43, u'Musset', u'Alfred de', u'gros'),
 (46, u'Hugo', u'Victor', u'moyen'),
 (47, u'Gary', u'Romain', u'petit'),
 (51, u'Lafargue', u'Paul', u'petit'),
 (53, u'Lamartine', u'Alphonse de', u'gros'),
 (54, u'Aurele', u'Marc', u'petit'),
 (55, u'Michelet', u'Jules', u'gros'),
 (56, u'Nerval', u'Gerard de', u'petit'),
 (57, u'Marx', u'Karl', u'gros'),
 (59, u'Nietzsche', u'Friedrich', u'petit'),
 (63, u'Maupassant', u'Guy de', u'petit'),
 (64, u'Platon', None, u'gros'),
 (65, u'Pascal', u'Blaise', u'petit'),
 (66, u'Perec', u'Georges', u'gros'),
 (67, u'Nin', u'Anais', u'petit'),
 (68, u'Prevert', u'Jacques', u'gros'),
 (69, u'Queneau', u'Raymond', u'petit'),
 (70, u'Paulhan', u'Jean', u'gros'),
 (71, u'Radiguet', u'Raymond', u'petit'),
 (72, u'Rabelais', u'Francois', u'gros'),
 (73, u'Poe', u'Allan Edgard', u'moyen'),
 (74, u'Rimbaud', u'Arthur', u'petit'),
 (76, u'Racine', u'Jean', u'gros'),
 (77, u'Rousseau', u'Jean-Jacques', u'petit'),
 (78, u'Sandier', u'Jules', u'moyen'),
 (79, u'Sade', u'Donatien Alphonse Fran\xbf\xbfs de', u'gros'),
 (81, u'Sartre', u'Jean-Paul', u'gros'),
 (83, u'Sophocle', None, u'gros'),
 (84, u'Sue', u'Eugene', u'moyen'),
 (85, u'Segalen', u'Victor', u'petit'),
 (86, u'Saint Exupery', u'Antoine de', u'gros'),
 (87, u'Segur', u'Comtesse de', u'gros'),
 (88, u'Shakespeare', u'William', u'petit'),
 (89, u'Stendhal', None, u'petit'),
 (90, u'Vian', u'Boris', u'petit'),
 (91, u'Verlaine', u'Paul', u'gros'),
 (93, u'Virgile', None, u'gros'),
 (95, u'Zorn', u'Fritz', u'moyen'),
 (98, u'Maturin', u'Robert', u'gros'),
 (99, u'Cesar', u'Jules', u'gros'),
 (101, u'Porthos', u'du Vallon', u'gros')]

__2.6__ Compare the content of _table_ 'RBA' and the _view_ 'buveurs_asec'. What differences do you see? Explain

Answer:

___
# PART III: Design the database schema for a marketplace

We consider the following scenario:

You are a developer for a game. In the game, there are several kinds of objects that the players can collect (e.g. magical flowers, gems, etc.). Players can also sell or buy objects from a marketplace that works in the following way: players declare some of the objects in their possession as “buyable”
with a price for each buyable object and then any player can buy items marked as buyable. When a player buys an item, the possession of the item is transferred to the buyer while the money corresponding to the item is transferred from the buyer to the seller. Note that, as long as the item is not sold, it still belongs to the player. Your goal is to
create a database for this marketplace.

The database schema you will develop needs to support players, the money each player has, the various types
of objects present in the game and how many objects of each kind each player has.Your database need to be able
to support the following kind of operations:

* Create a new type of object or add new players,
* Change the name of a type of objects or the name of a player,
* Attribute an object of a given type to a player,
* Increase or decrease the amount of money a player has,
* Retrieve the list of all the items that a player has,
* Compute the current balance of a player,
* Allow a player to mark one of their item as buyable with a given price,
* Allow a player to buy the cheapest item of a given type from the marketplace.

Ideally your schema should enforce the following constraints:

* All the objects that the players have correspond to some known type,
* Each object is possessed by exactly one player,
* Any single object cannot be marked twice as buyable, nor it can have two different prices (but two different objects of the same kind can have different prices),
* Any player has a positive amount of money.

__3.1__ Draw an entity-relationship model for the scenario.

_to answer, you can for example join a figure with the notebook or write the information related to the entity and relationship sets_

__3.2__ Deduce the relational scheme while precising the _primary_ and _foreign_ (if any) keys for each relation.